[project]
name = "tts-script"
version = "0.1.0"
description = "Made to create audio from text on the z-read platform"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "pika>=1.3.2",
    "pymongo>=4.10.1",
    "torch>=2.5.1",
    "tts>=0.22.0",
]
